name: Publish

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    
    env:
      Solution_Name: SCTools
      Build_Config: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Download NuGet dependencies
      run: dotnet restore $env:Solution_Name --source https://api.nuget.org/v3/index.json
      
    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Build_Config
    
    - name: Publish to folder
      run: dotnet publish $env:Solution_Name -c $env:Build_Config /p:PublishProfile=FolderProfile.pubxml --no-build
    
    - name: Create zip package
      uses: thedoctor0/zip-release@master
      with:
        directory: "./${{ env.Solution_Name }}/${{ env.Solution_Name }}/publish"
        filename: "${{ env.Solution_Name }}.zip"
    
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        name: "SC:Tools"
        artifacts: "${{ env.Solution_Name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
